### ISSUE TITLE
Filter by team?

### ISSUE THREAD

**Issue by mlsmzk** [quant-aq/py-quantaq#14]
Hello, I am wondering if filtering client device listing supports filtration by teaming. If so, would you have to know the team id, or would you use the title?

**Comment by dhhagan** [comment]
Hi @mlsmzk - so sorry for the delay on this. I really need to iron out notifications for our repositories so that we see these sooner. Yes, it is possible it two ways:

## 1. Query the team 

If you query the team itself, it returns a list of all devices on the team

## 2. Use the 'team' parameter on the `devices/` endpoint

Using `py-quantaq`, this would be `client.devices.list(team='team-name')`

Let us know if you have any questions!
